### ISSUE TITLE
which license does this project use?

### ISSUE THREAD

**Issue by berlinguyinca** [bytekast/springboot-aws-lambda#1]
dear sir,

thank you for your hard work. We would like to use this tool in one of our applications and embed it as a library. Could you provide a license, please?

kind regards

**Comment by bytekast** [comment]
hi @berlinguyinca - so sorry i missed this. i was on paternity leave when this issue was created. i just added the Apache license to the project. thanks

**Comment by berlinguyinca** [comment]
no issues and congratulations
